version: 2.1
jobs:
  build:
    working_directory: ~/aws-lambda-example
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: pipenv run pytest tests/
